// <auto-generated />
using System;
using Kyc.Aggregation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kyc.Aggregation.Infrastructure.Migrations
{
    [DbContext(typeof(KycDbContext))]
    partial class KycDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Kyc.Aggregation.Infrastructure.Persistence.CustomerKycSnapshotEntity", b =>
                {
                    b.Property<string>("Ssn")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Ssn");

                    b.HasIndex("FetchedAtUtc");

                    b.ToTable("CustomerKycSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
